### ISSUE TITLE
Loihi hardware as backend for brian2

### ISSUE THREAD

**Issue by tristanstoeber** [sagacitysite/brian2_loihi#13]
Hey guys,
now that you have an Loihi emulator in Brian2, wouldn't it be great to have a software package that translates Loihi-compatible Brian2 code directly to whatever languages Loihi uses? My long term goal would be to be able to chose Loihi simply as a simulation backend in Brian2. Are there any plans for that?
Best,
Tristan

**Comment by sagacitysite** [comment]
Hi Tristan,

we considered this in the discussion of our upcoming paper and it would indeed great to see this feature one day. Currently there is no concrete plan to implement this from our side (especially since my time is ending now). But if there is ongoing interest, maybe we can convince Andrew and/or Winni to continue with this :)

Carlo

**Comment by tristanstoeber** [comment]
Hey Carlo, thanks for your reply! There is definitely interest from my side. Happy to participate.
